In [1]:
# 4. Sa se scrie o functie sum_divisors_digits care preia un numar natural strict pozitiv si returneaza
# suma cifrelor divizorilor sai. Intr-o alta functie black_hole se apeleaza in mod repetat 
# sum_divisors_digits pe numerele rezultate, pana cand se atinge un numar maxim de iteratii (implicit
# 1000) sau se ajunge la numarul 15. Puteti crea alte functii auxiliare.
# Exemplul 1: se pleaca de la ; divizorii sunt ; suma cifrelor divizorilor este 
# , acesta fiind rezultatul apelului sum_divisors_digits(15) . Functia black_hole
# se opreste deci dupa un singur apel al functiei sum_divisors_digits .
# Exemplul 2: se pleaca de la ; divizorii sunt iar sum_divisors_digits(21) este 
# ; se reia in functia black_hole apelul functiei sum_divisors_digits pana la
# epuizarea numarului de apeluri sau potentiala stabilizare in 15.

def divisors(n: int):
    """
    Args:
        n: an integer
    Returns:
        list of all divisors of the argument
    
    """
    lst=[]
    for index in range(1, n+1):
        if n%index==0:
            lst.append(index)
    return lst

def sum_digits(number: int):
    """
    Args:
        number: an integer
    Returns:
        sum of all the digits existing in the given argument
    
    """
    s=0
    while number!=0:
        digit=number%10
        s=s+digit
        number=number//10
    return s
        

def sum_divisors_digits(n: int):
    """
    Args:
        n: an integer
    Returns:
        sum of all digits of the given argument's divisors
    
    """
    lst=divisors(n)
    s=0
    for element in lst:
        s=s+sum_digits(element)
    
    return s

def black_hole():
    """
    Args: none
    
    Returns:
        prints the sum of divisors of a given number
        
    This function stops the iterations of calculating the sum of all digits
    of an integer's divisors if 1000 steps were taken or if the sum returns 15.
    
    """
    it=0
    stop=False
    x=int(input("Number = "))
    while it<1000 and stop==False:
        sum_div=sum_divisors_digits(x)
        print(f"\nIteration {it+1}")
        print(f"Sum of divisors = {sum_div}")
        if sum_div == 15:
            stop=True
            print("Stoped.")
        it+=1
        x=sum_div
black_hole()
        

Number = 15

Iteration 1
Sum of divisors = 15
Stoped.


In [2]:
# 3. Pentru un vector NumPy dat, sa se calculeze toate ferestrele de o anumita lungime, cu o anumita dilatare.
# Lungimea unei ferestre inseamna numarul de elemente din vectorii rezultati, dilatare reprezinta peste cate
# elemente vecine se sare in construirea unei "ferestre".
# Exemple:
# v = np.arange(20), win_len=4, dilation=1 -> [0, 1, 2, 3], [1, 2, 3, 4], [2, 3, 4, 5], ...[16, 17, 18, 19]
# v = np.arange(20), win_len=3, dilation=2 -> [0, 2, 4], [1, 3, 5], ..., [15, 17, 19]
# Valorile implicite pentru win_len si dilation sunt 3, respectiv 1. Veti verifica in cadrul functiilor daca: 0 <
# win_len <= numarul de elemente din vector , dilation > 0 si daca pentru vectorul de intrare, 
# win_len si dilation date rezulta macar o fereastra; daca vreuna din aceste conditii nu se indeplineste, nu
# se executa restul functiei si se arunca exceptie (se pot folosi assertiuni sau aruncari de exceptii). Rezultatul se
# va da ca un tablou cu win_len coloane.



import numpy as np

    
def get_win(v: np.arange, it: int, win_len: int, dilatation: int):
    """
    Args:
        v: numpy array
        it: an integer meaning the actual iteration
        win_len: an integer - windows length
        dilatation: an integer
    
    Returns:
        a list with every element in the array
        depending on the windows length and dilatation at a specific 
        iteration
    
    """
    index=it
    iteration=0
    num_win=0
    lst=[]
    while index<len(v) and iteration<win_len:
        lst.append(index)
        iteration+=1
        index+=dilatation
    if iteration==win_len:
        return lst
    else:
        return []
    
    
    
def all_win():
    """
    Args: none
    Returns:
         this function creates a matrix having as rows all the
         lists with a specific number of elements in the array,
         windows length and dilatation
         the matrix is returned
   
    
    """
    
    win_len=3
    dilatation=1
    
    n=int(input("Number of elements = "))
    win_len=int(input("win_len = "))
    dilatation=int(input("dilatation = "))
    v=np.arange(n)
    if win_len<=0 or win_len>n:
        raise Exception("win_len must be > 0 and <= number of elements")
    if dilatation<0 or dilatation>n:
        raise Exception("dilatation must be > 0 and <= number of elements")
    
    lst=[]
    matrix=[]
    for index in range(0, n):
        lst=get_win(v, index, win_len, dilatation)
        if lst!=[]:
            matrix.append(lst)
    mat=np.matrix(matrix)
    return mat
    
print(all_win())

Number of elements = 20
win_len = 3
dilatation = 2
[[ 0  2  4]
 [ 1  3  5]
 [ 2  4  6]
 [ 3  5  7]
 [ 4  6  8]
 [ 5  7  9]
 [ 6  8 10]
 [ 7  9 11]
 [ 8 10 12]
 [ 9 11 13]
 [10 12 14]
 [11 13 15]
 [12 14 16]
 [13 15 17]
 [14 16 18]
 [15 17 19]]


In [15]:
# 5. Se da un vector v de numere floating point, un numar floating point x si un numar intreg k>0 , 
# k<=len(v) . Sa se scrie o functie care determina pozitiile celor mai apropiate k valori din v fata de x (k
# nearest neighbors, 1d)

    
# def get_min(v: np.ndarray, x: float):
#     """
#     Args:
#         v: array
#     Returns:
#         the nearest neighbor in v of x
    
#     """
#     minim=x-v[0]
#     for index in range(1, len(v)):
#         if x-v[index]<minim:
#             minim=x-v[index]
#     v.delete(minim)
#     return minim
    

def get_positions():
    """
    Args: none
    Returns:
        v: array created randomly
        first_k_list: a list with all k elements the nearest neighbors of x
    
    Exception:
        raises exception if k is bigger than len(v) or less than 0
    
    """
    number_elements=int(input("Number of elements = "))
    v=np.random.rand(number_elements, 1)
    k=int(input("k = "))
    x=float(input("x = "))
    
    dif=[]
    for element in v:
        dif.append(x-element)
    
    first_k_list=[]
    v_backup=v
    if k>len(dif) or k<=0:
        raise Exception("k must be less than len(v)")
    
    for index in range(0, k):
        minim=min(dif)
        first_k_list.append(v[dif.index(minim)])
        dif.remove(minim)
    
    return v, first_k_list
    

v=[]
first_k_list=[]
v, first_k_list=get_positions()
print(v)
print("Elements of v the nearest neighbors of x\n", first_k_list)

Number of elements = 6
k = 4
x = 0.6
[[0.20284371]
 [0.79130594]
 [0.65201554]
 [0.3282658 ]
 [0.71862947]
 [0.35147641]]
Elements of v the nearest neighbors of x
 [array([0.79130594]), array([0.3282658]), array([0.79130594]), array([0.65201554])]


In [ ]:
# 3. Sa se scrie o functie care primeste caile catre doua fisiere de tip text. Despre fiecare fiecare se stie ca are
# cate un numar pe linie (numarul de linii din fisiere este necunoscut apriori). Functia va returna un tuplu cu:
# lista de numere care apar in ambele fisiere si diferenta maxima care exista intre numerele din al doilea
# fisier si numerele din primul fisier. Numerele pot fi cu semn, intregi sau in virgula mobila (functia trebuie sa
# mearga in orice situatie). Incercati sa folositi functii predefinite din Python (sau NumPy) si collection
# comprehension.
# Exemplu: a.txt contine numerele 1, 2, 3, 4 (cate unul pe linie). b.txt contine 2, 3, 4, 10 (cate un numar pe linie).
# Functia va returna tuplul ([2, 3, 4], 9) . Numarul 9 este realizat de 10-1.


def file_tuple(file_name1 : str , file_name2: str):
    """
    Args:
        file_name1: first file name : str
        file_name2: second file name : str
    
    Returns:
        a list having the first element a list of the mutual 
        elements from both files; the second element from 
        the list returned is the maximum difference obtained 
        from the second file's maximum value and the 
        first one's minimum value.
    
    """
    f = open(file_name1, "r")
    g = open(file_name2, "r")
    tup1 = []
    tup2 = []
    for line in f:
        if type(line) is int or float:
            tup1.append(float(line))
        else:
            return 0
    for line in g:
        if type(line) is int or float:
            tup2.append(float(line))
        else:
            return 0
    lst = []
    for element in tup1:
        if element in tup2:
            lst.append(element)
    maxim = max(tup2)
    minim = min(tup1)

    return (lst, maxim - minim)

print(file_tuple("text1.txt", "text2.txt"))


In [16]:
#1. Scrieti o functie care determina daca un numar este egal cu suma divizorilor sai, mai putin numarul insusi.

#Exemplu: divizorii lui 6 sunt 1, 2, 3, 6; suma celor mai mici decat 6 este 1+2+3=6=numarul de plecare. Numarul
#8 nu este in aceasta situatie: . Folositi aceasta functie pentru a afisa toate numere cu
#proprietatea ceruta pana la un dat.




def verif(nr: int,s: int):
    """
        Se determina daca un numar este egal cu suma divizorilor sai
        
        Parametrii:
            nr : numarul dat
            aux : copia numarului
            s : suma divizorilor
        
        Returneaza: 1 daca suma divizorilor este egala cu nr dat, 0 in caz contrar
    """
    aux: int = nr
    for i in range (1,aux-1):
        if (aux%i == 0):
            s += i
            aux /= i
    if (s == nr):
        return 1
    else:
        return 0
    
print (verif(6,0))


1


In [17]:
#2. Scrieti o functie care determina daca un sir de caractere - presupus a fi scris cu litere mici - este sau nu
#palindrom. Un palindrom este un sir de caractere care citit de la dreapta la stanga are acelasi continut ca si
#citirea de la stanga la dreapta. In functie de valoarea unui indicator boolean ignore_spaces , avand
#valoarea implicita False , se vor ignora (elimina) sau nu spatiile. Daca sirul dat ca parametru nu are toate
#literele mici, se va arunca exceptie; documentatie exceptii in Python
#(https://www.w3schools.com/python/gloss_python_raise.asp).
#Exemple:
#is_palindrome('ele fac cafele', ignore_spaces=True) returneaza True ; is_palindrome('ele
#fac cafele') returneaza False . is_palindrome('Ele fac cafele') arunca o exceptie, indiferent 3/2/2021 Laborator2 - Jupyter Notebook
#localhost:8888/notebooks/Laborator2/2021/Laborator2.ipynb# 2/3
#de valoarea lui ignore_spaces .
#is_palindrome('abaac') returneaza False

def is_palindrom(word: str, ignore_spaces: bool) -> bool:
    """
        Se determina daca un sir de caractere - presupus a fi scris cu litere mici - este sau nu palindrom fara litere mari
        
        Parametrii:
            word : cuvantul testat
            ignore_spaces : booleanul care dicteaza daca programul va ignora spatiile goale sau nu
            letter : o variabila care i-a literele cuvantului la rand pentru a gasi Upper-case uri
            i : counter pentru cuvant
            j : counter invers pt cuvant
            ok : boolean care este True daca cuvantul este palindrom sau False in caz contrar
            
        Returneaza: True daca cuvantul este palindrom si respecta toate conditiile sau False daca nu si Exceptie daca exista litere mari
    
    """
    
    
    for letter in word:
        if(letter.isupper()):
            raise Exception("S-a gasit o litera mare")
            
    if(ignore_spaces == True): 
        word=word.replace(" ", "")
            
    
    i:int = 0
    j:int = len(word)-1
    ok:bool = 1
    while i < len(word) and j >= 0 and ok == 1:
        if(word[i] != word[j]):
            ok=0
        i += 1
        j -= 1
    if (ok == 1):
        return True
    else:
        return False
    
    
print (is_palindrom('ele fac cafele',True))

#ele fac cafele
#elefac caf ele

True


In [18]:
#5. Sa se scrie o functie care primeste doua dictionare si returneaza True daca primul dictionar este continut
#in al doilea si False altfel. Spunem ca un dictionar a este continut in dictionarul b daca toate cheile din 
#a se gasesc printre cheile din b si toate pentru orice cheie c din a , a[c] == b[c] . Incercati sa
#folositi functii predefinite din Python ( any, all ), tipuri de date incluse in Python si collection
#comprehension.

def verif_dict(a: dict,b: dict) -> bool:
    """
        Functia determina daca primul dictionar primit este inclus in al doi-lea dictionar
        
        Parametrii:
            a : dictionar dat
            b : dictionar dat
            
        Returneaza : True daca a este inclus in b si False daca nu sun tincluse
        
    """

    for i in a:
        ok :int =-1
        for j in b:
            if i==j:
                ok=j
        if ok==-1:
            return False
        else:
            return True

a={
    "nume":"Andrei",
    "varsta":"20"
}
b={
    "nume":"Andrei",
    "varsta":"20",
    "sex":"masculin"
}

print (verif_dict(a,b))

True


In [19]:
#1. Scrieti o functie care pentru un vector dat dat, returneaza diferenta de ordinul intai intre elementele sale: 
#. Scrieti apoi o alta functie care face acelasi lucru pentru o matrice, pe linii sau pe
#coloane.
#Exemple:
#a = np.array([1, 2, 10, 3]) ; diff1_vector(a) va returna vectorul NumPy cu continutul (1, 8,
#-7) .
#a = np.array([[1, 2, 3], [40, 50, 60]]) ; diff1_mat(a, axis=0) returneaza o matrice cu o
#singura linie, [[39, 48, 57]] . diff1_mat(a, axis=1) returneaza o matrice cu 2x2, [[1, 1], [10,
#10]] .

import numpy as np

def diferenta(a: np.array([], int))-> np.array([], int):
    """
        Functia calculeaza diferenta dintre elementele vectorului
        
        Parametrii:
            a : vectorul dat
            b : vectorul construit
            
        Return : returneaza diferenta de ordin I dintre elementele vectorului
    
    """
    b1: np.array([], int)
    b1=np.diff(a1)
    return b1
        
        
a1=np.array([1, 2, 10, 3])

print("Input array  : ", a1) 
print (diferenta(a1))


def diferenta(a: np.array([], int))-> np.array([], int):
    """
        Functia calculeaza diferenta dintre elementele vectorului
        
        Parametrii:
            a : matricea data
            b : vectorul construit
            
        Return : returneaza diferenta de ordin I dintre elementele vectorului
    
    """
    b2: np.array([], int)
    b2=np.diff(a, axis = 0)
    return b2

a2=np.array([[1, 2, 3], [40, 50, 60]])
print("Input array  : ", a2) 
print (diferenta(a2))

Input array  :  [ 1  2 10  3]
[ 1  8 -7]
Input array  :  [[ 1  2  3]
 [40 50 60]]
[[39 48 57]]


In [20]:
#2. Sa se scrie o functie care gaseste pozitiile maximelor locale dintr-un vector numpy. Un maxim local este o
#valoare care are in vecinii imediati (indicele curent , fara a iesi din vector) valori strict mai mici decat ea.
#Exemplu: [-1, 3, -7, 1, 2, 6, 0, 1] -> [1, 5, 7] .

def poz_max(a: np.array([], int)) -> np.array([], int):
    """
        Functia determina pozitiile pe care se afla maximele locale din vectorul a
        
        Parametrii:
            a : vectorul dat
        
        Returneaza : un vector cu pozitiile pe care se afla maximele locale
            
    """
    b=np.array([])
    if(a[0]>a[1]):
        b=np.append(b,0)
        
    for i in range (1,len(a)-2):
        if(a[i-1]<a[i] and a[i+1]<a[i]):
            b=np.append(b,i)
            
    if(a[len(a)-1]>a[len(a)-2]):
        b=np.append(b,len(a)-1)
    return b

a=np.array([-1, 3, -7, 1, 2, 6, 0, 1])


print("Input array  : ", a)
print (poz_max(a))



Input array  :  [-1  3 -7  1  2  6  0  1]
[1. 5. 7.]
